src/components/Dropdown/Dropdown.js
src/components/List/List.js

- removed unnecessary state manipulation 
- Made variable declaration more consistent
- Removed unnecessary variables 
ex) variables that are only used to hold a temp state of another variable
- Cleaned up list component code
- Converted Dropdown component to class component (Solution to bug below)
- Fixed bug where if there was value present in Dropdown component the code would break.
- Fixed bug where Dropdown in List component would not have a default selected value

cleaned up list component code

---

src/components/Dropdown/Dropdown.js
src/components/List/List.js
src/components/Unlist/Unlist.js

- Cleaned up code in getMyOrders function
- All order information is now stored in an array of objects under the "myOrders" state
- All order labels ( what you see in dropdown menu ) is stored under the "orderLabels" state
- Added Dropdown to Unlist component
- Added automatic orderID state change when dropdown item is clicked ( fills input box with proper id )
- Commented what getMyOrders does

Added dropdown menu to Unlist component

---

package-lock.json
src/components/Bulletin/Bulletin.js
src/components/ContractDetails/ContractDetails.js
src/components/CreateContract/CreateContract.js
src/components/Main/Main.js
src/components/MyPortfolio/MyPortfolio.js
src/components/Table/Cell/Cell.js
src/components/Table/Table.js

- Changed dates to be displayed in UTC
- Fixed token naming
- Created logic for Tables component to take an array of object as rows prop
- Added links to contract,token, and oracle addresses to contract details component.
- Contract details will now display token address  ( if there is one on target click ).

Issue #53 Fix & Contract dates fix

---

src/reducers/statusReducer.js

Correct set connection status in `./statusReducers`

Correct set connection status

---

src/AppRouter.js
src/components/CreateContractFormComponent.js
src/components/datepicker.js

Included: 
- Fix the datepicker for create contract
Affects: 
- AppRouter.js
- components/datepicker.js (renamed to Datepicker.js)
- components/CreateContractFormComponent

Datepicker fix

---

src/components/CreateContract.js

Included: 
- Fix error display in portfolio by correcting error condition for error message rendering
Affects:
- /components/CreateContract.js

Fix error display in portfolio

---

package-lock.json
src/actions/userActions.js
src/components/MyPositions.js
src/components/MyTransactions.js
src/reducers/contractReducer.js
src/reducers/userReducer.js

Small changes to the My Portfolio page.

Dan site updates

---

src/AppRouter.js
src/components/Header.js
src/style.css

Included: 
- Refactor header connection status indicator
- Adjust header spacing
Affected:
- /components/Header.js
- /AppRouter.js
- /style.css

Refactor header connection status indicator

---

src/actions/orderActions.js
src/components/Bulletin.js
src/components/Buy.js
src/components/CashOut.js
src/components/InputText.js
src/components/Landing.js
src/components/List.js
src/components/ListFormContainer.js
src/components/OrderBook.js
src/components/RecentTrades.js
src/components/Unlist.js
src/components/UnlistFormContainer.js
src/reducers/orderReducer.js
src/reducers/userReducer.js

Included:
- Numerous corrections to eliminate console errors on load up of /bulletin page
Affects:
- src/actions/orderActions.js
- src/components/Bulletin.js
- src/components/Buy.js
- src/components/CashOut.js
- src/components/InputText.js
- src/components/Landing.js
- src/components/List.js
- src/components/ListFormContainer.js
- src/components/OrderBook.js
- src/components/RecentTrades.js
- src/components/Unlist.js
- src/components/UnlistFormContainer.js
- src/reducers/orderReducer.js
- src/reducers/userReducer.js

Misc bug fixes to eliminate errors on Bulletin load up

---

src/actions/statusActions.js
src/components/requireConnection.js
src/reducers/statusReducer.js

Included:
- Add verified to status.connectStatus; 
- Set verified in statusActions checkUserConnection; 
- Add verified as prop to requireConnection component;
- Update shouldNavigateAway to check verified before redirect
Affects:
- actions/statusActions.js
- components/requireConnection.js
- reducers/statusReducer.js

Update connection status check 

---

src/components/List.js

Included:
- Fix props errors;
- Bind button toggle to this;
Affects:
- components/List.js

Fix props errors and button toggle in List

---

src/components/Buy.js
src/components/Unlist.js

Included:
- Corrected null in error message logic 
Affects:
-components/Buy.js
-components/Unlist.js

Correct null values in order components

---

src/__tests__/actions/statusActions.test.js

Includes:
- Add tests for status actions 
Affects:
`/__tests__/actions/statusActions.test.js`

Add tests for statusActions

---

src/__tests__/reducers/statusReducer.test.js

Included: 
- Add tests for status reducer
Affects:
`/__tests__/reducers/statusReducer.test.js`

Add tests for status reducer

---

src/reducers/userReducer.js

Included: 
- Change initialState.userOrders to empty array 
- Add cashOutError to initialState 
Affects: 
`/reducers/userReducer.js `

Correct user reducer initial state

---

src/__tests__/reducers/contractReducer.test.js

Included: 
- Add tests of contract reducer 
Affects: 
`/__tests__/reducers/contractReducer.test.js`

Test contract reducer

---

src/reducers/contractReducer.js

Included: 
- Correct reducer initial state and set contract funded
Affects:
`/reducers/contractReducer.js`

contract reducer corrections

---

src/__tests__/reducers/userReducer.test.js
src/reducers/userReducer.js

Included:
- Set initial state for cashOutError
- Update userOrders to action payload
Affects:
`/__tests__/reducers/userReducer.test.js`
`reducers/userReducer.js`

Get all userReducer tests passing

---

src/__tests__/reducers/selectedReducer.test.js

Included: 
- Add tests for selected reducer
Affects: 
`/__tests__/reducers/selectedReducer.js`

Add tests of selected reducer

---

src/__tests__/reducers/dataReducer.test.js

Included: 
- Add tests of data reducer 
Affects: 
`/__tests__/reducers/dataReducer.test.js`

Add tests of data reducer

---

src/__tests__/reducers/orderReducer.test.js
src/reducers/orderReducer.js

Included: 
- Add tests of order reducer
- Corrected state returned from set list order approved
Affects: 
`/__tests__/reducers/orderReducer.test.js`
`/reducers/orderReducer.js`

order reducer tests

---

src/components/BuyFormContainer.js
src/components/CashOutFormContainer.js
src/components/CreateContractFormContainer.js
src/components/ListFormContainer.js
src/components/UnlistFormContainer.js

Included: 
- Refactor form containers redux-form wrapper and redux store connect
Affects:
`/components/BuyFormContainer.js`
`/components/CashOutFormContainer.js`
`/components/CreateContractFormContainer.js`
`/components/ListFormContainer.js`
`/components/UnlistFormContainer.js`

Refactor form containers store/form connection

---

src/components/BuyFormComponent.js
src/components/BuyFormContainer.js
src/components/CashOutFormComponent.js
src/components/CashOutFormContainer.js
src/components/CreateContractFormComponent.js
src/components/CreateContractFormContainer.js
src/components/InputNumber.js
src/components/InputText.js
src/components/ListFormComponent.js
src/components/ListFormContainer.js
src/components/Select.js
src/components/UnlistFormComponent.js
src/components/UnlistFormContainer.js

Includes: 
- In form containers, add validate function for inputs and give to redux-form
- In form components, add submitting prop to disable submit button
- In input components, add touched and error props, and error message
Affects:
```
src/components/BuyFormComponent.js
src/components/BuyFormContainer.js
src/components/CashOutFormComponent.js
src/components/CashOutFormContainer.js
src/components/CreateContractFormComponent.js
src/components/CreateContractFormContainer.js
src/components/InputNumber.js
src/components/InputText.js
src/components/ListFormComponent.js
src/components/ListFormContainer.js
src/components/Select.js
src/components/UnlistFormComponent.js
src/components/UnlistFormContainer.js
```

Add input validation to forms

---

package-lock.json
src/components/Bulletin.js
src/components/Buy.js
src/components/BuyFormContainer.js
src/components/ListFormContainer.js
src/components/OrderBook.js
src/components/RecentTrades.js
src/style.css

Working on buttons and order modal

Updated bulletin style

---

src/__tests__/actions/statusActions.test.js
src/actions/contractActions.js
src/actions/orderActions.js
src/actions/statusActions.js
src/actions/userActions.js

Included:
- Remove set processing from data fetch actions
Affects: 
`src/actions/contractActions.js
src/actions/orderActions.js
src/actions/statusActions.js
src/actions/userActions.js`

Remove set processing from data fetch actions

---

src/__tests__/actions/statusActions.test.js
src/__tests__/reducers/contractReducer.test.js
src/__tests__/reducers/orderReducer.test.js
src/__tests__/reducers/statusReducer.test.js
src/reducers/orderReducer.js

Included: 
- Fix tests for contractReducer, orderReducer and statusReducer
- Update orderReducer to reflect changes in action
Affects: 
-`src/__tests__/actions/statusActions.test.js`
-`src/__tests__/reducers/contractReducer.test.js`
-`src/__tests__/reducers/orderReducer.test.js`
-`src/__tests__/reducers/statusReducer.test.js`

Fix reducer tests and reducer

---

src/actions/userActions.js
src/components/CreateContractFormComponent.js
src/components/SendFundsFormComponent.js

Reverts DecentralizedDerivatives/DRCT_standard_DApp#237

Revert "Fix cashout value"

---

src/api/api.js
src/components/PriceChart.js

This PR regards to issue #219.
* Add asset label and price tooltip;
* Add a `1 minute` button;
* Add API call to get minutely prices;
* Save asset prices to component state to avoid a call each time a button is pressed;
* Group the data points.

Improve Graph
